name: Issue Report
description: File an issue report related to UWB. This should ONLY be used for issues (such as bugs or something broken)!
title: "[Issue] "
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        Hello, and thank you for reporting an issue with Unity Web Browser (UWB)!
        When filling out the information below, please try to provide as much details as you can, the more you provide, the more likely we can help and fix something.

        **Questions and features should be asked via [Discussions](https://github.com/Voltstro-Studios/UnityWebBrowser/discussions)**
  
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you experiencing this issue on?
      options:
        - Windows x64
        - Linux x64
        - MacOS x64
        - MacOS arm64
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: What version of UWB are you using?
      placeholder: '2.2.0'
    validations:
      required: true
  
  - type: input
    id: unity-version
    attributes:
      label: What Unity version are you running?
      placeholder: 2021.3.11f1
    validations:
      required: true
  
  - type: textarea
    id: issue-describe
    attributes:
      label: Describe what the issue you are experiencing is.
      description: Tells us what the issue exactly is.
      placeholder: Please provide a description on the issue
    validations:
      required: true
  
  - type: textarea
    id: reproducible-steps
    attributes:
      label: Provide reproducible steps for this issue.
      description: Providing reproducible steps always helps. You could also provide a project with the issue here. If its a Unity project please delete the cache folder (`/Library`) and other unnecessary files from it (Such as `/Temp`, `/obj`, `*.csproj` files and builds).
      placeholder: Please provide reproducible steps
      value: |
        1. I did this.
        2. I then did that.
        3. Boom! Issue.
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Any additional info you like to provide?
      description: Provide images, use code blocks for code or other info if you think it will help. Remember more info is always better.
    validations:
      required: false